#############################################################################
# Makefile for building: build/debug/baracuda
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  baracuda.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile baracuda.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_BUILDNUM_=55 -DCUDA_DIR=/usr/local/cuda-7.5 -DPATH=/usr/bin/:/usr/local/bin -DNVCCBIN=/usr/local/cuda-7.5/bin/nvcc -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/debug/.moc -Ibuild/debug/.ui
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/local/cuda-7.5/lib64 -L/usr/X11R6/lib64 -ldl -lcudart -L/opt/cuda/lib -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/debug/.obj/

####### Files

SOURCES       = src/cuda_drvapi_dynlink.c \
		src/main.cpp \
		src/mainwindow.cpp \
		src/op.cpp \
		src/opchain.cpp \
		src/opcomposer.cpp \
		src/gpu.cpp \
		src/cudacompil.cpp \
		src/brick.cpp \
		src/moduleslistmodel.cpp \
		src/gpumodule.cpp \
		src/modulelist.cpp \
		src/modulelistitem.cpp \
		src/cuglpixelbuffer.cpp \
		src/glrendererwidget.cpp \
		src/timelineview.cpp \
		src/histogram.cpp \
		src/textedit.cpp \
		src/glrenderer.cpp \
		src/highlighter.cpp \
		src/sourceedit.cpp \
		src/bartime.cpp build/debug/.qrc/qrc_baracuda.cpp \
		build/debug/.moc/moc_mainwindow.cpp \
		build/debug/.moc/moc_opcomposer.cpp \
		build/debug/.moc/moc_moduleslistmodel.cpp \
		build/debug/.moc/moc_modulelist.cpp \
		build/debug/.moc/moc_compilation.cpp \
		build/debug/.moc/moc_glrendererwidget.cpp \
		build/debug/.moc/moc_timelineview.cpp \
		build/debug/.moc/moc_histogram.cpp \
		build/debug/.moc/moc_textedit.cpp \
		build/debug/.moc/moc_glrenderer.cpp \
		build/debug/.moc/moc_highlighter.cpp \
		build/debug/.moc/moc_sourceedit.cpp
OBJECTS       = build/debug/.obj/cuda_drvapi_dynlink.o \
		build/debug/.obj/main.o \
		build/debug/.obj/mainwindow.o \
		build/debug/.obj/op.o \
		build/debug/.obj/opchain.o \
		build/debug/.obj/opcomposer.o \
		build/debug/.obj/gpu.o \
		build/debug/.obj/cudacompil.o \
		build/debug/.obj/brick.o \
		build/debug/.obj/moduleslistmodel.o \
		build/debug/.obj/gpumodule.o \
		build/debug/.obj/modulelist.o \
		build/debug/.obj/modulelistitem.o \
		build/debug/.obj/cuglpixelbuffer.o \
		build/debug/.obj/glrendererwidget.o \
		build/debug/.obj/timelineview.o \
		build/debug/.obj/histogram.o \
		build/debug/.obj/textedit.o \
		build/debug/.obj/glrenderer.o \
		build/debug/.obj/highlighter.o \
		build/debug/.obj/sourceedit.o \
		build/debug/.obj/bartime.o \
		build/debug/.obj/qrc_baracuda.o \
		build/debug/.obj/moc_mainwindow.o \
		build/debug/.obj/moc_opcomposer.o \
		build/debug/.obj/moc_moduleslistmodel.o \
		build/debug/.obj/moc_modulelist.o \
		build/debug/.obj/moc_compilation.o \
		build/debug/.obj/moc_glrendererwidget.o \
		build/debug/.obj/moc_timelineview.o \
		build/debug/.obj/moc_histogram.o \
		build/debug/.obj/moc_textedit.o \
		build/debug/.obj/moc_glrenderer.o \
		build/debug/.obj/moc_highlighter.o \
		build/debug/.obj/moc_sourceedit.o
DIST          = readme.md \
		src/ui_mainwindow.h \
		kernels/channels.cu \
		kernels/test.cu \
		kernels/baracuda.hcu \
		kernels/vecmath.hcu \
		kernels/circle.cu \
		kernels/ribbons.cu \
		kernels/ribbons-glsl.cu \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		baracuda.pro src/cuda_drvapi_dynlink.c \
		src/main.cpp \
		src/mainwindow.cpp \
		src/op.cpp \
		src/opchain.cpp \
		src/opcomposer.cpp \
		src/gpu.cpp \
		src/cudacompil.cpp \
		src/brick.cpp \
		src/moduleslistmodel.cpp \
		src/gpumodule.cpp \
		src/modulelist.cpp \
		src/modulelistitem.cpp \
		src/cuglpixelbuffer.cpp \
		src/glrendererwidget.cpp \
		src/timelineview.cpp \
		src/histogram.cpp \
		src/textedit.cpp \
		src/glrenderer.cpp \
		src/highlighter.cpp \
		src/sourceedit.cpp \
		src/bartime.cpp
QMAKE_TARGET  = baracuda
DESTDIR       = build/debug/#avoid trailing-slash linebreak
TARGET        = build/debug/baracuda


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/debug/.ui/ui_mainwindow.h build/debug/.ui/ui_about.h $(OBJECTS)  
	@test -d build/debug/ || mkdir -p build/debug/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: baracuda.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		baracuda.pro \
		src/baracuda.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile baracuda.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
baracuda.pro:
src/baracuda.qrc:
/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile baracuda.pro

qmake_all: FORCE

dist: 
	@test -d build/debug/.obj/baracuda1.0.0 || mkdir -p build/debug/.obj/baracuda1.0.0
	$(COPY_FILE) --parents $(DIST) build/debug/.obj/baracuda1.0.0/ && $(COPY_FILE) --parents src/baracuda.qrc build/debug/.obj/baracuda1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/helper_cuda_drvapi.h src/op.h src/bartypes.h src/opchain.h src/opcomposer.h src/gpu.h src/cudacompil.h src/brick.h src/moduleslistmodel.h src/gpumodule.h src/modulelist.h src/modulelistitem.h src/compilation.h src/cuglpixelbuffer.h src/glrendererwidget.h src/timelineview.h src/histogram.h src/textedit.h src/glrenderer.h src/highlighter.h src/sourceedit.h src/baracuda.h src/bartime.h build/debug/.obj/baracuda1.0.0/ && $(COPY_FILE) --parents src/cuda_drvapi_dynlink.c src/main.cpp src/mainwindow.cpp src/op.cpp src/opchain.cpp src/opcomposer.cpp src/gpu.cpp src/cudacompil.cpp src/brick.cpp src/moduleslistmodel.cpp src/gpumodule.cpp src/modulelist.cpp src/modulelistitem.cpp src/cuglpixelbuffer.cpp src/glrendererwidget.cpp src/timelineview.cpp src/histogram.cpp src/textedit.cpp src/glrenderer.cpp src/highlighter.cpp src/sourceedit.cpp src/bartime.cpp build/debug/.obj/baracuda1.0.0/ && $(COPY_FILE) --parents src/mainwindow.ui src/about.ui build/debug/.obj/baracuda1.0.0/ && (cd `dirname build/debug/.obj/baracuda1.0.0` && $(TAR) baracuda1.0.0.tar baracuda1.0.0 && $(COMPRESS) baracuda1.0.0.tar) && $(MOVE) `dirname build/debug/.obj/baracuda1.0.0`/baracuda1.0.0.tar.gz . && $(DEL_FILE) -r build/debug/.obj/baracuda1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) build/debug/$(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

distclean: extraclean

extraclean:
	find . -name "*.ptx" -exec rm -v {} \;

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_cuda_make_all:
compiler_cuda_clean:
compiler_rcc_make_all: build/debug/.qrc/qrc_baracuda.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/debug/.qrc/qrc_baracuda.cpp
build/debug/.qrc/qrc_baracuda.cpp: src/baracuda.qrc \
		src/baracuda.jpg
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name baracuda src/baracuda.qrc -o build/debug/.qrc/qrc_baracuda.cpp

compiler_moc_header_make_all: build/debug/.moc/moc_mainwindow.cpp build/debug/.moc/moc_opcomposer.cpp build/debug/.moc/moc_moduleslistmodel.cpp build/debug/.moc/moc_modulelist.cpp build/debug/.moc/moc_compilation.cpp build/debug/.moc/moc_glrendererwidget.cpp build/debug/.moc/moc_timelineview.cpp build/debug/.moc/moc_histogram.cpp build/debug/.moc/moc_textedit.cpp build/debug/.moc/moc_glrenderer.cpp build/debug/.moc/moc_highlighter.cpp build/debug/.moc/moc_sourceedit.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/debug/.moc/moc_mainwindow.cpp build/debug/.moc/moc_opcomposer.cpp build/debug/.moc/moc_moduleslistmodel.cpp build/debug/.moc/moc_modulelist.cpp build/debug/.moc/moc_compilation.cpp build/debug/.moc/moc_glrendererwidget.cpp build/debug/.moc/moc_timelineview.cpp build/debug/.moc/moc_histogram.cpp build/debug/.moc/moc_textedit.cpp build/debug/.moc/moc_glrenderer.cpp build/debug/.moc/moc_highlighter.cpp build/debug/.moc/moc_sourceedit.cpp
build/debug/.moc/moc_mainwindow.cpp: src/gpu.h \
		src/baracuda.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/moduleslistmodel.h \
		src/gpumodule.h \
		src/bartypes.h \
		src/brick.h \
		src/op.h \
		src/cuglpixelbuffer.h \
		src/bartime.h \
		src/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/baracuda.git -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/mainwindow.h -o build/debug/.moc/moc_mainwindow.cpp

build/debug/.moc/moc_opcomposer.cpp: src/modulelist.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/bartypes.h \
		src/brick.h \
		src/op.h \
		src/cuglpixelbuffer.h \
		src/opcomposer.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/baracuda.git -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/opcomposer.h -o build/debug/.moc/moc_opcomposer.cpp

build/debug/.moc/moc_moduleslistmodel.cpp: src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/bartypes.h \
		src/moduleslistmodel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/baracuda.git -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/moduleslistmodel.h -o build/debug/.moc/moc_moduleslistmodel.cpp

build/debug/.moc/moc_modulelist.cpp: src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/bartypes.h \
		src/brick.h \
		src/op.h \
		src/cuglpixelbuffer.h \
		src/modulelist.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/baracuda.git -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/modulelist.h -o build/debug/.moc/moc_modulelist.cpp

build/debug/.moc/moc_compilation.cpp: src/cudacompil.h \
		src/bartypes.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/gpu.h \
		src/baracuda.h \
		src/compilation.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/baracuda.git -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/compilation.h -o build/debug/.moc/moc_compilation.cpp

build/debug/.moc/moc_glrendererwidget.cpp: src/op.h \
		src/bartypes.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/cuglpixelbuffer.h \
		src/gpu.h \
		src/baracuda.h \
		src/glrendererwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/baracuda.git -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/glrendererwidget.h -o build/debug/.moc/moc_glrendererwidget.cpp

build/debug/.moc/moc_timelineview.cpp: src/bartime.h \
		src/timelineview.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/baracuda.git -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/timelineview.h -o build/debug/.moc/moc_timelineview.cpp

build/debug/.moc/moc_histogram.cpp: src/cuglpixelbuffer.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/glrendererwidget.h \
		src/op.h \
		src/bartypes.h \
		src/gpumodule.h \
		src/gpu.h \
		src/baracuda.h \
		src/histogram.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/baracuda.git -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/histogram.h -o build/debug/.moc/moc_histogram.cpp

build/debug/.moc/moc_textedit.cpp: src/baracuda.h \
		src/highlighter.h \
		src/brick.h \
		src/bartypes.h \
		src/op.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/cuglpixelbuffer.h \
		src/textedit.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/baracuda.git -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/textedit.h -o build/debug/.moc/moc_textedit.cpp

build/debug/.moc/moc_glrenderer.cpp: src/op.h \
		src/bartypes.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/cuglpixelbuffer.h \
		src/gpu.h \
		src/baracuda.h \
		src/glrenderer.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/baracuda.git -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/glrenderer.h -o build/debug/.moc/moc_glrenderer.cpp

build/debug/.moc/moc_highlighter.cpp: src/highlighter.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/baracuda.git -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/highlighter.h -o build/debug/.moc/moc_highlighter.cpp

build/debug/.moc/moc_sourceedit.cpp: src/textedit.h \
		src/baracuda.h \
		src/highlighter.h \
		src/brick.h \
		src/bartypes.h \
		src/op.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/cuglpixelbuffer.h \
		src/cudacompil.h \
		src/gpu.h \
		src/sourceedit.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/baracuda.git -I/usr/local/cuda-7.5/include -I/usr/local/cuda-7.5/samples/common/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/sourceedit.h -o build/debug/.moc/moc_sourceedit.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/debug/.ui/ui_mainwindow.h build/debug/.ui/ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) build/debug/.ui/ui_mainwindow.h build/debug/.ui/ui_about.h
build/debug/.ui/ui_mainwindow.h: src/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/mainwindow.ui -o build/debug/.ui/ui_mainwindow.h

build/debug/.ui/ui_about.h: src/about.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/about.ui -o build/debug/.ui/ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/debug/.obj/cuda_drvapi_dynlink.o: src/cuda_drvapi_dynlink.c src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/cuda_drvapi_dynlink.o src/cuda_drvapi_dynlink.c

build/debug/.obj/main.o: src/main.cpp src/mainwindow.h \
		src/gpu.h \
		src/baracuda.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/moduleslistmodel.h \
		src/gpumodule.h \
		src/bartypes.h \
		src/brick.h \
		src/op.h \
		src/cuglpixelbuffer.h \
		src/bartime.h \
		src/cudacompil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/main.o src/main.cpp

build/debug/.obj/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/gpu.h \
		src/baracuda.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/moduleslistmodel.h \
		src/gpumodule.h \
		src/bartypes.h \
		src/brick.h \
		src/op.h \
		src/cuglpixelbuffer.h \
		src/bartime.h \
		src/ui_mainwindow.h \
		src/modulelist.h \
		src/glrendererwidget.h \
		src/opcomposer.h \
		src/textedit.h \
		src/highlighter.h \
		src/timelineview.h \
		src/ui_about.h \
		src/cudacompil.h \
		src/compilation.h \
		src/histogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/mainwindow.o src/mainwindow.cpp

build/debug/.obj/op.o: src/op.cpp src/op.h \
		src/bartypes.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/cuglpixelbuffer.h \
		src/baracuda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/op.o src/op.cpp

build/debug/.obj/opchain.o: src/opchain.cpp src/opchain.h \
		src/bartypes.h \
		src/op.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/cuglpixelbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/opchain.o src/opchain.cpp

build/debug/.obj/opcomposer.o: src/opcomposer.cpp src/opcomposer.h \
		src/modulelist.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/bartypes.h \
		src/brick.h \
		src/op.h \
		src/cuglpixelbuffer.h \
		src/modulelistitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/opcomposer.o src/opcomposer.cpp

build/debug/.obj/gpu.o: src/gpu.cpp src/gpu.h \
		src/baracuda.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/gpu.o src/gpu.cpp

build/debug/.obj/cudacompil.o: src/cudacompil.cpp src/cudacompil.h \
		src/bartypes.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/gpu.h \
		src/baracuda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/cudacompil.o src/cudacompil.cpp

build/debug/.obj/brick.o: src/brick.cpp src/brick.h \
		src/bartypes.h \
		src/op.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/cuglpixelbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/brick.o src/brick.cpp

build/debug/.obj/moduleslistmodel.o: src/moduleslistmodel.cpp src/moduleslistmodel.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/bartypes.h \
		src/modulelistitem.h \
		src/modulelist.h \
		src/brick.h \
		src/op.h \
		src/cuglpixelbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moduleslistmodel.o src/moduleslistmodel.cpp

build/debug/.obj/gpumodule.o: src/gpumodule.cpp src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/bartypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/gpumodule.o src/gpumodule.cpp

build/debug/.obj/modulelist.o: src/modulelist.cpp src/modulelist.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/bartypes.h \
		src/brick.h \
		src/op.h \
		src/cuglpixelbuffer.h \
		src/modulelistitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/modulelist.o src/modulelist.cpp

build/debug/.obj/modulelistitem.o: src/modulelistitem.cpp src/modulelistitem.h \
		src/modulelist.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/bartypes.h \
		src/brick.h \
		src/op.h \
		src/cuglpixelbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/modulelistitem.o src/modulelistitem.cpp

build/debug/.obj/cuglpixelbuffer.o: src/cuglpixelbuffer.cpp src/cuglpixelbuffer.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/baracuda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/cuglpixelbuffer.o src/cuglpixelbuffer.cpp

build/debug/.obj/glrendererwidget.o: src/glrendererwidget.cpp src/glrendererwidget.h \
		src/op.h \
		src/bartypes.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/cuglpixelbuffer.h \
		src/gpu.h \
		src/baracuda.h \
		src/bartime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/glrendererwidget.o src/glrendererwidget.cpp

build/debug/.obj/timelineview.o: src/timelineview.cpp src/timelineview.h \
		src/bartime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/timelineview.o src/timelineview.cpp

build/debug/.obj/histogram.o: src/histogram.cpp src/histogram.h \
		src/cuglpixelbuffer.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/glrendererwidget.h \
		src/op.h \
		src/bartypes.h \
		src/gpumodule.h \
		src/gpu.h \
		src/baracuda.h \
		src/cudacompil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/histogram.o src/histogram.cpp

build/debug/.obj/textedit.o: src/textedit.cpp src/textedit.h \
		src/baracuda.h \
		src/highlighter.h \
		src/brick.h \
		src/bartypes.h \
		src/op.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/cuglpixelbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/textedit.o src/textedit.cpp

build/debug/.obj/glrenderer.o: src/glrenderer.cpp src/glrenderer.h \
		src/op.h \
		src/bartypes.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/cuglpixelbuffer.h \
		src/gpu.h \
		src/baracuda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/glrenderer.o src/glrenderer.cpp

build/debug/.obj/highlighter.o: src/highlighter.cpp src/highlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/highlighter.o src/highlighter.cpp

build/debug/.obj/sourceedit.o: src/sourceedit.cpp src/sourceedit.h \
		src/textedit.h \
		src/baracuda.h \
		src/highlighter.h \
		src/brick.h \
		src/bartypes.h \
		src/op.h \
		src/gpumodule.h \
		src/cuda_drvapi_dynlink.h \
		src/cuda_drvapi_dynlink_cuda.h \
		src/cuda_drvapi_dynlink_gl.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_std.h \
		/usr/local/cuda-7.5/samples/common/inc/GL/freeglut_ext.h \
		src/helper_cuda_drvapi.h \
		/usr/local/cuda-7.5/samples/common/inc/helper_string.h \
		/usr/local/cuda-7.5/samples/common/inc/drvapi_error_string.h \
		src/cuglpixelbuffer.h \
		src/cudacompil.h \
		src/gpu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/sourceedit.o src/sourceedit.cpp

build/debug/.obj/bartime.o: src/bartime.cpp src/bartime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/bartime.o src/bartime.cpp

build/debug/.obj/qrc_baracuda.o: build/debug/.qrc/qrc_baracuda.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/qrc_baracuda.o build/debug/.qrc/qrc_baracuda.cpp

build/debug/.obj/moc_mainwindow.o: build/debug/.moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_mainwindow.o build/debug/.moc/moc_mainwindow.cpp

build/debug/.obj/moc_opcomposer.o: build/debug/.moc/moc_opcomposer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_opcomposer.o build/debug/.moc/moc_opcomposer.cpp

build/debug/.obj/moc_moduleslistmodel.o: build/debug/.moc/moc_moduleslistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_moduleslistmodel.o build/debug/.moc/moc_moduleslistmodel.cpp

build/debug/.obj/moc_modulelist.o: build/debug/.moc/moc_modulelist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_modulelist.o build/debug/.moc/moc_modulelist.cpp

build/debug/.obj/moc_compilation.o: build/debug/.moc/moc_compilation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_compilation.o build/debug/.moc/moc_compilation.cpp

build/debug/.obj/moc_glrendererwidget.o: build/debug/.moc/moc_glrendererwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_glrendererwidget.o build/debug/.moc/moc_glrendererwidget.cpp

build/debug/.obj/moc_timelineview.o: build/debug/.moc/moc_timelineview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_timelineview.o build/debug/.moc/moc_timelineview.cpp

build/debug/.obj/moc_histogram.o: build/debug/.moc/moc_histogram.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_histogram.o build/debug/.moc/moc_histogram.cpp

build/debug/.obj/moc_textedit.o: build/debug/.moc/moc_textedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_textedit.o build/debug/.moc/moc_textedit.cpp

build/debug/.obj/moc_glrenderer.o: build/debug/.moc/moc_glrenderer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_glrenderer.o build/debug/.moc/moc_glrenderer.cpp

build/debug/.obj/moc_highlighter.o: build/debug/.moc/moc_highlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_highlighter.o build/debug/.moc/moc_highlighter.cpp

build/debug/.obj/moc_sourceedit.o: build/debug/.moc/moc_sourceedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_sourceedit.o build/debug/.moc/moc_sourceedit.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

