#############################################################################
# Makefile for building: src
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  src.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile src.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I /usr/include/x86_64-linux-gnu/qt5/QtWidgets
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = baracuda.c \
		baracuda.cpp \
		brick.cpp \
		compilation.cpp \
		compiler.cpp \
		cuda_drvapi_dynlink.c \
		cudacompil.cpp \
		cudapbo.cpp \
		cuglpixelbuffer.cpp \
		glrenderer.cpp \
		glrendererwidget.cpp \
		GLWidget.cpp \
		gpu.cpp \
		gpumodule.cpp \
		highlighter.cpp \
		histogram.cpp \
		main.cpp \
		mainwindow.cpp \
		mandelbrot_ptxdump.c \
		modulelist.cpp \
		modulelistitem.cpp \
		moduleslistmodel.cpp \
		neutral_ptxdump.c \
		op.cpp \
		opchain.cpp \
		opcomposer.cpp \
		red_ptx_ptxdump.c \
		red_ptxdump.c \
		simplePBO.cpp \
		system_linux.cpp \
		tests.cpp \
		textedit.cpp \
		tiFunc.cpp \
		timedtest_ptxdump.c \
		timelineview.cpp \
		tiTimer.cpp \
		tests/testTimer.cpp qrc_baracuda.cpp \
		moc_compilation.cpp \
		moc_glrenderer.cpp \
		moc_glrendererwidget.cpp \
		moc_GLWidget.cpp \
		moc_highlighter.cpp \
		moc_histogram.cpp \
		moc_mainwindow.cpp \
		moc_modulelist.cpp \
		moc_moduleslistmodel.cpp \
		moc_opcomposer.cpp \
		moc_textedit.cpp \
		moc_timelineview.cpp
OBJECTS       = baracuda.o \
		baracuda.o \
		brick.o \
		compilation.o \
		compiler.o \
		cuda_drvapi_dynlink.o \
		cudacompil.o \
		cudapbo.o \
		cuglpixelbuffer.o \
		glrenderer.o \
		glrendererwidget.o \
		GLWidget.o \
		gpu.o \
		gpumodule.o \
		highlighter.o \
		histogram.o \
		main.o \
		mainwindow.o \
		mandelbrot_ptxdump.o \
		modulelist.o \
		modulelistitem.o \
		moduleslistmodel.o \
		neutral_ptxdump.o \
		op.o \
		opchain.o \
		opcomposer.o \
		red_ptx_ptxdump.o \
		red_ptxdump.o \
		simplePBO.o \
		system_linux.o \
		tests.o \
		textedit.o \
		tiFunc.o \
		timedtest_ptxdump.o \
		timelineview.o \
		tiTimer.o \
		testTimer.o \
		qrc_baracuda.o \
		moc_compilation.o \
		moc_glrenderer.o \
		moc_glrendererwidget.o \
		moc_GLWidget.o \
		moc_highlighter.o \
		moc_histogram.o \
		moc_mainwindow.o \
		moc_modulelist.o \
		moc_moduleslistmodel.o \
		moc_opcomposer.o \
		moc_textedit.o \
		moc_timelineview.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		src.pro baracuda.c \
		baracuda.cpp \
		brick.cpp \
		compilation.cpp \
		compiler.cpp \
		cuda_drvapi_dynlink.c \
		cudacompil.cpp \
		cudapbo.cpp \
		cuglpixelbuffer.cpp \
		glrenderer.cpp \
		glrendererwidget.cpp \
		GLWidget.cpp \
		gpu.cpp \
		gpumodule.cpp \
		highlighter.cpp \
		histogram.cpp \
		main.cpp \
		mainwindow.cpp \
		mandelbrot_ptxdump.c \
		modulelist.cpp \
		modulelistitem.cpp \
		moduleslistmodel.cpp \
		neutral_ptxdump.c \
		op.cpp \
		opchain.cpp \
		opcomposer.cpp \
		red_ptx_ptxdump.c \
		red_ptxdump.c \
		simplePBO.cpp \
		system_linux.cpp \
		tests.cpp \
		textedit.cpp \
		tiFunc.cpp \
		timedtest_ptxdump.c \
		timelineview.cpp \
		tiTimer.cpp \
		tests/testTimer.cpp
QMAKE_TARGET  = src
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = src


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: src.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		src.pro \
		baracuda.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile src.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
src.pro:
baracuda.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile src.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/src1.0.0 || mkdir -p .tmp/src1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/src1.0.0/ && $(COPY_FILE) --parents baracuda.qrc .tmp/src1.0.0/ && $(COPY_FILE) --parents baracuda.h bartypes.h brick.h compilation.h compiler.h cuda_drvapi_dynlink.h cuda_drvapi_dynlink_cuda.h cuda_drvapi_dynlink_d3d.h cuda_drvapi_dynlink_gl.h cudacompil.h cudapbo.h cuglpixelbuffer.h drvapi_error_string.h glrenderer.h glrendererwidget.h GLWidget.h gpu.h gpumodule.h helper_cuda_drvapi.h helper_string.h highlighter.h histogram.h keywords.h mainwindow.h mandelbrot_ptxdump.h modulelist.h modulelistitem.h moduleslistmodel.h neutral_ptxdump.h op.h opchain.h opcomposer.h red_ptx.h red_ptx_ptxdump.h red_ptxdump.h simplePBO.h textedit.h tiFunc.h timedtest_ptxdump.h timelineview.h tiTimer.h ui_about.h ui_mainwindow.h .tmp/src1.0.0/ && $(COPY_FILE) --parents baracuda.c baracuda.cpp brick.cpp compilation.cpp compiler.cpp cuda_drvapi_dynlink.c cudacompil.cpp cudapbo.cpp cuglpixelbuffer.cpp glrenderer.cpp glrendererwidget.cpp GLWidget.cpp gpu.cpp gpumodule.cpp highlighter.cpp histogram.cpp main.cpp mainwindow.cpp mandelbrot_ptxdump.c modulelist.cpp modulelistitem.cpp moduleslistmodel.cpp neutral_ptxdump.c op.cpp opchain.cpp opcomposer.cpp red_ptx_ptxdump.c red_ptxdump.c simplePBO.cpp system_linux.cpp tests.cpp textedit.cpp tiFunc.cpp timedtest_ptxdump.c timelineview.cpp tiTimer.cpp tests/testTimer.cpp .tmp/src1.0.0/ && (cd `dirname .tmp/src1.0.0` && $(TAR) src1.0.0.tar src1.0.0 && $(COMPRESS) src1.0.0.tar) && $(MOVE) `dirname .tmp/src1.0.0`/src1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/src1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_baracuda.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_baracuda.cpp
qrc_baracuda.cpp: baracuda.qrc \
		baracuda.jpg
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name baracuda baracuda.qrc -o qrc_baracuda.cpp

compiler_moc_header_make_all: moc_compilation.cpp moc_glrenderer.cpp moc_glrendererwidget.cpp moc_GLWidget.cpp moc_highlighter.cpp moc_histogram.cpp moc_mainwindow.cpp moc_modulelist.cpp moc_moduleslistmodel.cpp moc_opcomposer.cpp moc_textedit.cpp moc_timelineview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_compilation.cpp moc_glrenderer.cpp moc_glrendererwidget.cpp moc_GLWidget.cpp moc_highlighter.cpp moc_histogram.cpp moc_mainwindow.cpp moc_modulelist.cpp moc_moduleslistmodel.cpp moc_opcomposer.cpp moc_textedit.cpp moc_timelineview.cpp
moc_compilation.cpp: cudacompil.h \
		bartypes.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		gpu.h \
		tiTimer.h \
		tiFunc.h \
		compilation.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/oldbaracuda/src -I/home/heimdall/project/oldbaracuda/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include compilation.h -o moc_compilation.cpp

moc_glrenderer.cpp: op.h \
		bartypes.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		cuglpixelbuffer.h \
		tiTimer.h \
		tiFunc.h \
		gpu.h \
		glrenderer.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/oldbaracuda/src -I/home/heimdall/project/oldbaracuda/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include glrenderer.h -o moc_glrenderer.cpp

moc_glrendererwidget.cpp: op.h \
		bartypes.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		cuglpixelbuffer.h \
		tiTimer.h \
		tiFunc.h \
		gpu.h \
		glrendererwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/oldbaracuda/src -I/home/heimdall/project/oldbaracuda/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include glrendererwidget.h -o moc_glrendererwidget.cpp

moc_GLWidget.cpp: cudapbo.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		tiTimer.h \
		tiFunc.h \
		GLWidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/oldbaracuda/src -I/home/heimdall/project/oldbaracuda/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include GLWidget.h -o moc_GLWidget.cpp

moc_highlighter.cpp: highlighter.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/oldbaracuda/src -I/home/heimdall/project/oldbaracuda/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include highlighter.h -o moc_highlighter.cpp

moc_histogram.cpp: cuglpixelbuffer.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		tiTimer.h \
		tiFunc.h \
		glrendererwidget.h \
		op.h \
		bartypes.h \
		gpumodule.h \
		gpu.h \
		histogram.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/oldbaracuda/src -I/home/heimdall/project/oldbaracuda/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include histogram.h -o moc_histogram.cpp

moc_mainwindow.cpp: gpu.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		tiTimer.h \
		tiFunc.h \
		moduleslistmodel.h \
		gpumodule.h \
		bartypes.h \
		brick.h \
		op.h \
		cuglpixelbuffer.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/oldbaracuda/src -I/home/heimdall/project/oldbaracuda/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_modulelist.cpp: gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		bartypes.h \
		brick.h \
		op.h \
		cuglpixelbuffer.h \
		tiTimer.h \
		tiFunc.h \
		modulelist.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/oldbaracuda/src -I/home/heimdall/project/oldbaracuda/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include modulelist.h -o moc_modulelist.cpp

moc_moduleslistmodel.cpp: gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		bartypes.h \
		moduleslistmodel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/oldbaracuda/src -I/home/heimdall/project/oldbaracuda/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include moduleslistmodel.h -o moc_moduleslistmodel.cpp

moc_opcomposer.cpp: modulelist.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		bartypes.h \
		brick.h \
		op.h \
		cuglpixelbuffer.h \
		tiTimer.h \
		tiFunc.h \
		opcomposer.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/oldbaracuda/src -I/home/heimdall/project/oldbaracuda/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include opcomposer.h -o moc_opcomposer.cpp

moc_textedit.cpp: highlighter.h \
		cudacompil.h \
		bartypes.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		gpu.h \
		tiTimer.h \
		tiFunc.h \
		textedit.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/oldbaracuda/src -I/home/heimdall/project/oldbaracuda/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include textedit.h -o moc_textedit.cpp

moc_timelineview.cpp: timelineview.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/heimdall/project/oldbaracuda/src -I/home/heimdall/project/oldbaracuda/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include timelineview.h -o moc_timelineview.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

baracuda.o: baracuda.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o baracuda.o baracuda.c

baracuda.o: baracuda.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o baracuda.o baracuda.cpp

brick.o: brick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brick.o brick.cpp

compilation.o: compilation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compilation.o compilation.cpp

compiler.o: compiler.cpp compiler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compiler.o compiler.cpp

cuda_drvapi_dynlink.o: cuda_drvapi_dynlink.c cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cuda_drvapi_dynlink.o cuda_drvapi_dynlink.c

cudacompil.o: cudacompil.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cudacompil.o cudacompil.cpp

cudapbo.o: cudapbo.cpp cudapbo.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		tiTimer.h \
		tiFunc.h \
		neutral_ptxdump.h \
		timedtest_ptxdump.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cudapbo.o cudapbo.cpp

cuglpixelbuffer.o: cuglpixelbuffer.cpp cuglpixelbuffer.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		tiTimer.h \
		tiFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cuglpixelbuffer.o cuglpixelbuffer.cpp

glrenderer.o: glrenderer.cpp glrenderer.h \
		op.h \
		bartypes.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		cuglpixelbuffer.h \
		tiTimer.h \
		tiFunc.h \
		gpu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glrenderer.o glrenderer.cpp

glrendererwidget.o: glrendererwidget.cpp glrendererwidget.h \
		op.h \
		bartypes.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		cuglpixelbuffer.h \
		tiTimer.h \
		tiFunc.h \
		gpu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glrendererwidget.o glrendererwidget.cpp

GLWidget.o: GLWidget.cpp GLWidget.h \
		cudapbo.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		tiTimer.h \
		tiFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLWidget.o GLWidget.cpp

gpu.o: gpu.cpp gpu.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		tiTimer.h \
		tiFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpu.o gpu.cpp

gpumodule.o: gpumodule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpumodule.o gpumodule.cpp

highlighter.o: highlighter.cpp highlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o highlighter.o highlighter.cpp

histogram.o: histogram.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o histogram.o histogram.cpp

main.o: main.cpp cudacompil.h \
		bartypes.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		gpu.h \
		tiTimer.h \
		tiFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp compilation.h \
		cudacompil.h \
		bartypes.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		gpu.h \
		tiTimer.h \
		tiFunc.h \
		moduleslistmodel.h \
		histogram.h \
		cuglpixelbuffer.h \
		glrendererwidget.h \
		op.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mandelbrot_ptxdump.o: mandelbrot_ptxdump.c mandelbrot_ptxdump.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o mandelbrot_ptxdump.o mandelbrot_ptxdump.c

modulelist.o: modulelist.cpp modulelist.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		bartypes.h \
		brick.h \
		op.h \
		cuglpixelbuffer.h \
		tiTimer.h \
		tiFunc.h \
		modulelistitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modulelist.o modulelist.cpp

modulelistitem.o: modulelistitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modulelistitem.o modulelistitem.cpp

moduleslistmodel.o: moduleslistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moduleslistmodel.o moduleslistmodel.cpp

neutral_ptxdump.o: neutral_ptxdump.c neutral_ptxdump.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o neutral_ptxdump.o neutral_ptxdump.c

op.o: op.cpp op.h \
		bartypes.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		cuglpixelbuffer.h \
		tiTimer.h \
		tiFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o op.o op.cpp

opchain.o: opchain.cpp opchain.h \
		bartypes.h \
		op.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		cuglpixelbuffer.h \
		tiTimer.h \
		tiFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o opchain.o opchain.cpp

opcomposer.o: opcomposer.cpp modulelistitem.h \
		modulelist.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		bartypes.h \
		brick.h \
		op.h \
		cuglpixelbuffer.h \
		tiTimer.h \
		tiFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o opcomposer.o opcomposer.cpp

red_ptx_ptxdump.o: red_ptx_ptxdump.c red_ptx_ptxdump.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o red_ptx_ptxdump.o red_ptx_ptxdump.c

red_ptxdump.o: red_ptxdump.c red_ptxdump.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o red_ptxdump.o red_ptxdump.c

simplePBO.o: simplePBO.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simplePBO.o simplePBO.cpp

system_linux.o: system_linux.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o system_linux.o system_linux.cpp

tests.o: tests.cpp tiTimer.h \
		tiFunc.h \
		cudacompil.h \
		bartypes.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		gpu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tests.o tests.cpp

textedit.o: textedit.cpp textedit.h \
		highlighter.h \
		cudacompil.h \
		bartypes.h \
		gpumodule.h \
		cuda_drvapi_dynlink.h \
		cuda_drvapi_dynlink_cuda.h \
		cuda_drvapi_dynlink_gl.h \
		helper_cuda_drvapi.h \
		helper_string.h \
		drvapi_error_string.h \
		gpu.h \
		tiTimer.h \
		tiFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textedit.o textedit.cpp

tiFunc.o: tiFunc.cpp tiFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tiFunc.o tiFunc.cpp

timedtest_ptxdump.o: timedtest_ptxdump.c timedtest_ptxdump.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o timedtest_ptxdump.o timedtest_ptxdump.c

timelineview.o: timelineview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timelineview.o timelineview.cpp

tiTimer.o: tiTimer.cpp tiTimer.h \
		tiFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tiTimer.o tiTimer.cpp

testTimer.o: tests/testTimer.cpp tiTimer.h \
		tiFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testTimer.o tests/testTimer.cpp

qrc_baracuda.o: qrc_baracuda.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_baracuda.o qrc_baracuda.cpp

moc_compilation.o: moc_compilation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_compilation.o moc_compilation.cpp

moc_glrenderer.o: moc_glrenderer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glrenderer.o moc_glrenderer.cpp

moc_glrendererwidget.o: moc_glrendererwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glrendererwidget.o moc_glrendererwidget.cpp

moc_GLWidget.o: moc_GLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GLWidget.o moc_GLWidget.cpp

moc_highlighter.o: moc_highlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_highlighter.o moc_highlighter.cpp

moc_histogram.o: moc_histogram.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_histogram.o moc_histogram.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_modulelist.o: moc_modulelist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modulelist.o moc_modulelist.cpp

moc_moduleslistmodel.o: moc_moduleslistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_moduleslistmodel.o moc_moduleslistmodel.cpp

moc_opcomposer.o: moc_opcomposer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_opcomposer.o moc_opcomposer.cpp

moc_textedit.o: moc_textedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textedit.o moc_textedit.cpp

moc_timelineview.o: moc_timelineview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timelineview.o moc_timelineview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

